[toolchain]
channel = "stable"
components = [
  "rust-src",
  "rust-analyzer",
  "clippy",
  "rustfmt",
  "llvm-tools-preview"
]
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu"]
profile = "default"
