[package]
name = "sqlrustgo"
version = "1.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
hex = "0.4"
bytes = "1.0"
lru-cache = "0.1.2"
ctrlc = "3.5.2"
serde_json = "1.0"

[dev-dependencies]
serde_json = "1.0"
tempfile = "3.25.0"

[[test]]
name = "project_test"
path = "tests/project_test.rs"

[[test]]
name = "ci_test"
path = "tests/ci_test.rs"
